name: 'ci'

on:
  push:
    branches: [ '*' ]
  pull_request:
    types: [ opened, edited, reopened, synchronize, review_requested ]
    branches: [ '*' ]
  workflow_call:

env:
  COVER_PKG: 'github.com/btnguyen2k/godynamo'
  AWS_REGION: 'us-east-1'
  AWS_ACCESS_KEY_ID: 'DUMMYID'
  AWS_SECRET_ACCESS_KEY: 'DUMMYKEY'
  AWS_DYNAMODB_ENDPOINT: 'http://localhost:8000'
  AWS_DYNAMODB_URL: 'Endpoint=http://localhost:8000'

jobs:
  testLocal:
    name: Test against AWS DynamoDB local
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v4
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Start AWS DynamoDB local server
      run: docker run -d --name dynamodb -p 8000:8000 amazon/dynamodb-local -jar DynamoDBLocal.jar -inMemory -sharedDb
    - name: Test
      run: |
        export AWS_REGION="us-east-1"
        export AWS_ACCESS_KEY_ID="DUMMYID"
        export AWS_SECRET_ACCESS_KEY="DUMMYKEY"
        export AWS_DYNAMODB_ENDPOINT="http://localhost:8000"
        export AWS_DYNAMODB_URL="Endpoint=http://localhost:8000"
        go test -v -timeout 9999s -count 1 -p 1 -cover -coverprofile coverage_local.txt .
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: local
        name: local
